name: CI Mentoria

# gatilhos
on:
  workflow_dispatch

jobs:
  tests:

    # [config so] (windows/linux/mac, chrome/firefox/edge, ...)
    runs-on: ubuntu-latest

    # [variaveis] (variaveis de ambiente, chaves de acesso a plataformas, etc.)
    env:
      API_BASE_URL: 'http://localhost:3000'
      PORT: 4000

    # [acoes ou passo]
    steps:

      # [projetos] (aplicacoes, projetos de teste, etc.)
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      # [deps do projeto] (node/npm, java/maven,gradle, python/pip, ...)
      - name: Instalando as dependências
        run: npm install

      - name: Iniciar o servidor de mocks
        run: npm run mock-server &

      - name: Iniciar o servidor de aplicacao
        run: npm run server &

      - name: Executar os testes
        run: npx cypress run
      
      
    
